# Generated by Django 5.0.1 on 2024-02-07 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BMW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chevrolet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ford',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Honda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lexus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mazda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MercedesBenz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nissan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('AN', 'Andijan'), ('BU', 'Bukhara'), ('FA', 'Fergana'), ('JI', 'Jizzakh'), ('XO', 'Khorezm'), ('NA', 'Namangan'), ('NW', 'Navoiy'), ('QA', 'Qashqadaryo'), ('SA', 'Samarkand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TA', 'Tashkent')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subaru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Toyota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Volkswagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=16)),
                ('car_position', models.CharField(default='не указано', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterTypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('GIDRO', 'гидроцикл'), ('KATER', 'катер'), ('BOAT', 'лодка'), ('YAXTA', 'яхта'), ('ENGINE', 'лодочный мотор,двигатель')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audi_passenger_cars', to='Cars.audi')),
                ('bmw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmw_passenger_cars', to='Cars.bmw')),
                ('chevrolet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chevrolet_passenger_cars', to='Cars.chevrolet')),
                ('ford', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ford_passenger_cars', to='Cars.ford')),
                ('honda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honda_passenger_cars', to='Cars.honda')),
                ('lexus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexus_passenger_cars', to='Cars.lexus')),
                ('mazda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazda_passenger_cars', to='Cars.mazda')),
                ('mercedes_benz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercedes_benz_passenger_cars', to='Cars.mercedesbenz')),
                ('nissan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nissan_passenger_cars', to='Cars.nissan')),
                ('subaru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subaru_passenger_cars', to='Cars.subaru')),
                ('toyota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.toyota')),
                ('volkswagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volkswagen_passenger_cars', to='Cars.volkswagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PassengerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_body', models.CharField(max_length=128)),
                ('drive_unit', models.CharField(max_length=128)),
                ('engine_type', models.CharField(max_length=128)),
                ('transmission', models.CharField(max_length=128)),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=128)),
                ('search', models.TextField()),
                ('is_bargain', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_leasetoown', models.BooleanField(default=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(2500), django.core.validators.MaxValueValidator(6500)])),
                ('year_of_issue', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('carbrands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.carbrands')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_field', models.TextField()),
                ('is_bargain', models.BooleanField(default=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(2500), django.core.validators.MaxValueValidator(6500)])),
                ('year_of_issue', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaterTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_field', models.TextField()),
                ('is_bargain', models.BooleanField(default=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(2500), django.core.validators.MaxValueValidator(6500)])),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.region')),
                ('water_type_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.watertypecar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motorcycles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_cycles', to='Cars.motorcycles')),
                ('passengercar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_car', to='Cars.passengercar')),
                ('watertransport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watert_ransport', to='Cars.watertransport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
