# Generated by Django 5.0.1 on 2024-02-07 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesAndElectronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_field', models.TextField()),
                ('region', models.CharField(choices=[('AN', 'Andijan'), ('BU', 'Bukhara'), ('FA', 'Fergana'), ('JI', 'Jizzakh'), ('XO', 'Khorezm'), ('NA', 'Namangan'), ('NW', 'Navoiy'), ('QA', 'Qashqadaryo'), ('SA', 'Samarkand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TA', 'Tashkent')], max_length=16)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('USED', 'б/у'), ('NEW', 'новые')], max_length=16)),
                ('is_bargain', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumablesAndOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_field', models.TextField()),
                ('region', models.CharField(choices=[('AN', 'Andijan'), ('BU', 'Bukhara'), ('FA', 'Fergana'), ('JI', 'Jizzakh'), ('XO', 'Khorezm'), ('NA', 'Namangan'), ('NW', 'Navoiy'), ('QA', 'Qashqadaryo'), ('SA', 'Samarkand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TA', 'Tashkent')], max_length=16)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('USED', 'б/у'), ('NEW', 'новые')], max_length=16)),
                ('is_bargain', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_field', models.TextField()),
                ('region', models.CharField(choices=[('AN', 'Andijan'), ('BU', 'Bukhara'), ('FA', 'Fergana'), ('JI', 'Jizzakh'), ('XO', 'Khorezm'), ('NA', 'Namangan'), ('NW', 'Navoiy'), ('QA', 'Qashqadaryo'), ('SA', 'Samarkand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TA', 'Tashkent')], max_length=16)),
                ('disk_type', models.CharField(choices=[('LEGKO', 'Легкосплавные'), ('STEEL', 'Стальные')], max_length=16)),
                ('size_width', models.FloatField()),
                ('size_fasteners', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('USED', 'б/у'), ('NEW', 'новые')], max_length=16)),
                ('is_bargain', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_field', models.TextField()),
                ('size_width', models.FloatField()),
                ('size_profile', models.FloatField()),
                ('size_diametr', models.IntegerField()),
                ('region', models.CharField(choices=[('AN', 'Andijan'), ('BU', 'Bukhara'), ('FA', 'Fergana'), ('JI', 'Jizzakh'), ('XO', 'Khorezm'), ('NA', 'Namangan'), ('NW', 'Navoiy'), ('QA', 'Qashqadaryo'), ('SA', 'Samarkand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TA', 'Tashkent')], max_length=16)),
                ('season', models.CharField(choices=[('SUM', 'Летние'), ('WIN', 'Зимние'), ('ALL', 'Все сезоны')], max_length=16)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('USED', 'б/у'), ('NEW', 'новые')], max_length=16)),
                ('is_bargain', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoAndAutopart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_field', models.TextField()),
                ('region', models.CharField(choices=[('AN', 'Andijan'), ('BU', 'Bukhara'), ('FA', 'Fergana'), ('JI', 'Jizzakh'), ('XO', 'Khorezm'), ('NA', 'Namangan'), ('NW', 'Navoiy'), ('QA', 'Qashqadaryo'), ('SA', 'Samarkand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TA', 'Tashkent')], max_length=16)),
                ('condition', models.CharField(choices=[('USED', 'б/у'), ('NEW', 'новые')], max_length=16)),
                ('carbrand', models.CharField(choices=[('Toyota', 'toyota_choices'), ('Honda', 'honda_choices'), ('Nissan', 'nissan_choices'), ('BMW', 'bmw_choices'), ('MercedesBenz', 'mercedes_benz_choices'), ('Audi', 'audi_choices'), ('Volkswagen', 'volkswagen_choices'), ('Lexus', 'lexus_choices'), ('Subaru', 'subaru_choices'), ('Mazda', 'mazda_choices'), ('Ford', 'ford_choices'), ('Chevrolet', 'chevrolet_choices')], max_length=16)),
                ('price', models.IntegerField()),
                ('is_bargain', models.BooleanField(default=False)),
                ('with_photo', models.ImageField(upload_to='media/')),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.carmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(choices=[('AN', 'Andijan'), ('BU', 'Bukhara'), ('FA', 'Fergana'), ('JI', 'Jizzakh'), ('XO', 'Khorezm'), ('NA', 'Namangan'), ('NW', 'Navoiy'), ('QA', 'Qashqadaryo'), ('SA', 'Samarkand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TA', 'Tashkent')], max_length=16)),
                ('carbrands', models.CharField(choices=[('Toyota', 'toyota_choices'), ('Honda', 'honda_choices'), ('Nissan', 'nissan_choices'), ('BMW', 'bmw_choices'), ('MercedesBenz', 'mercedes_benz_choices'), ('Audi', 'audi_choices'), ('Volkswagen', 'volkswagen_choices'), ('Lexus', 'lexus_choices'), ('Subaru', 'subaru_choices'), ('Mazda', 'mazda_choices'), ('Ford', 'ford_choices'), ('Chevrolet', 'chevrolet_choices')], max_length=16)),
                ('search_field', models.TextField()),
                ('search_from_text', models.BooleanField(default=False)),
                ('with_photo', models.ImageField(upload_to='media/')),
                ('is_bargain', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('USED', 'б/у'), ('NEW', 'новые')], max_length=4)),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.carmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoPartsAndDeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spareparts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autoparts.spareparts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
