# Generated by Django 5.0.1 on 2024-02-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AN', 'Andijan'), ('BU', 'Bukhara'), ('FA', 'Fergana'), ('JI', 'Jizzakh'), ('XO', 'Khorezm'), ('NA', 'Namangan'), ('NW', 'Navoiy'), ('QA', 'Qashqadaryo'), ('SA', 'Samarkand'), ('SI', 'Sirdaryo'), ('SU', 'Surxondaryo'), ('TA', 'Tashkent')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_field', models.TextField()),
                ('search_from_text', models.BooleanField(default=False)),
                ('with_photo', models.ImageField(upload_to='media/')),
                ('is_bargain', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('condition', models.CharField(choices=[('USED', 'б/у'), ('NEW', 'новые')], max_length=4)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autoparts.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoPartsAndDeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spareparts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autoparts.spareparts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
